ARG NODE_VERSION=20-alpine

FROM node:${NODE_VERSION} AS deps
WORKDIR /app
COPY package*.json ./
RUN npm ci

FROM deps AS build
ARG VITE_API_BASE_URL=/api/v1
ARG VITE_USE_MOCKS=false
ARG VITE_AUTH_MODE=chat-auth
ARG VITE_APP_SYSTEM_CODE=HRM
# These absolute-URL vars are baked as placeholders at build time and replaced
# at container startup by deploy/docker/entrypoint.sh using runtime env vars.
ARG VITE_AUTH_API_BASE_URL=__VITE_AUTH_API_BASE_URL__
ARG VITE_AUTH_SERVICE_BASE_URL=__VITE_AUTH_SERVICE_BASE_URL__
ARG VITE_AUTH_SERVICE_LOGIN_URL=__VITE_AUTH_SERVICE_LOGIN_URL__
ARG VITE_AUTH_SERVICE_LOGOUT_URL=__VITE_AUTH_SERVICE_LOGOUT_URL__
ARG VITE_AUTH_SERVICE_CLIENT_ID=hr-web-client
ARG VITE_AUTH_SERVICE_REDIRECT_URI=/auth/callback
# Backward-compat aliases — also substituted at runtime
ARG VITE_CHAT_AUTH_BASE_URL=__VITE_AUTH_SERVICE_BASE_URL__
ARG VITE_CHAT_AUTH_LOGIN_URL=__VITE_AUTH_SERVICE_LOGIN_URL__
ARG VITE_CHAT_AUTH_LOGOUT_URL=__VITE_AUTH_SERVICE_LOGOUT_URL__
ARG VITE_CHAT_AUTH_CLIENT_ID=hr-web-client
ARG VITE_CHAT_AUTH_REDIRECT_URI=/auth/callback

ENV VITE_API_BASE_URL=${VITE_API_BASE_URL}
ENV VITE_USE_MOCKS=${VITE_USE_MOCKS}
ENV VITE_AUTH_MODE=${VITE_AUTH_MODE}
ENV VITE_APP_SYSTEM_CODE=${VITE_APP_SYSTEM_CODE}
ENV VITE_AUTH_API_BASE_URL=${VITE_AUTH_API_BASE_URL}
ENV VITE_AUTH_SERVICE_BASE_URL=${VITE_AUTH_SERVICE_BASE_URL}
ENV VITE_AUTH_SERVICE_LOGIN_URL=${VITE_AUTH_SERVICE_LOGIN_URL}
ENV VITE_AUTH_SERVICE_LOGOUT_URL=${VITE_AUTH_SERVICE_LOGOUT_URL}
ENV VITE_AUTH_SERVICE_CLIENT_ID=${VITE_AUTH_SERVICE_CLIENT_ID}
ENV VITE_AUTH_SERVICE_REDIRECT_URI=${VITE_AUTH_SERVICE_REDIRECT_URI}
ENV VITE_CHAT_AUTH_BASE_URL=${VITE_CHAT_AUTH_BASE_URL}
ENV VITE_CHAT_AUTH_LOGIN_URL=${VITE_CHAT_AUTH_LOGIN_URL}
ENV VITE_CHAT_AUTH_LOGOUT_URL=${VITE_CHAT_AUTH_LOGOUT_URL}
ENV VITE_CHAT_AUTH_CLIENT_ID=${VITE_CHAT_AUTH_CLIENT_ID}
ENV VITE_CHAT_AUTH_REDIRECT_URI=${VITE_CHAT_AUTH_REDIRECT_URI}

WORKDIR /app
COPY . .
RUN npm run build

FROM nginx:1.27-alpine AS production
COPY deploy/nginx/default.conf.template /etc/nginx/templates/default.conf.template
COPY deploy/docker/entrypoint.sh /docker-entrypoint.d/40-inject-env.sh
RUN chmod +x /docker-entrypoint.d/40-inject-env.sh
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=5 \
  CMD wget -qO- http://127.0.0.1/healthz >/dev/null || exit 1

CMD ["nginx", "-g", "daemon off;"]
