export const ROUTES = {
  login: '/login',
  authCallback: '/auth/callback',
  root: '/',
  dashboard: '/dashboard',
  employees: '/employees',
  units: '/organization/units',
  departments: '/organization/departments',
  positions: '/organization/positions',
  movements: '/movements',
  contracts: '/contracts',
  leave: '/leave',
  attendance: '/attendance',
  onboarding: '/onboarding',
  offboarding: '/offboarding',
  imports: '/imports',
  auditLogs: '/audit-logs',
  settings: '/settings',
} as const;

