export const ROUTES = {
  login: '/login',
  authCallback: '/auth/callback',
  root: '/',
  dashboard: '/dashboard',
  employees: '/employees',
  businessSectors: '/organization/business-sectors',
  units: '/organization/units',
  departments: '/organization/departments',
  positions: '/organization/positions',
  movements: '/movements',
  contracts: '/contracts',
  leave: '/leave',
  attendance: '/attendance',
  attendanceMapping: '/attendance/mapping',
  onboarding: '/onboarding',
  offboarding: '/offboarding',
  imports: '/imports',
  auditLogs: '/audit-logs',
  settings: '/settings',
  accounts: '/accounts',
  roles: '/roles',
  permissions: '/permissions',
  permissionGroups: '/permission-groups',
  changePassword: '/change-password',
} as const;
