export const STATUS_OPTIONS = [
  'ACTIVE',
  'INACTIVE',
  'PROBATION',
  'TERMINATED',
  'DRAFT',
  'SUBMITTED',
  'APPROVED',
  'REJECTED',
  'CANCELLED',
  'COMPLETED',
  'FAILED',
  'PARTIAL_SUCCESS',
  'IN_PROGRESS',
] as const;

export const EMPLOYMENT_STATUS_OPTIONS = ['ACTIVE', 'PROBATION', 'TERMINATED', 'INACTIVE'] as const;
export const MOVEMENT_TYPE_OPTIONS = ['TRANSFER', 'STATUS_CHANGE', 'TERMINATION', 'PROMOTION'] as const;
export const LEAVE_TYPE_OPTIONS = ['ANNUAL', 'SICK', 'UNPAID', 'MATERNITY'] as const;
export const CONTRACT_TYPE_OPTIONS = ['LABOR', 'PROBATION', 'CONSULTING'] as const;
export const ATTENDANCE_SOURCE_OPTIONS = ['MANUAL', 'MACHINE', 'IMPORT'] as const;

